/**
 * Utilities for order number formatting and URL parameter parsing.
 * Note: Order numbers (RE-XXXXX) are generated by the DB trigger, not frontend.
 */

/** Format order number with hash prefix for display: "RE-00142" → "#RE-00142" */
export function formatOrderNumber(orderNumber: string): string {
  return `#${orderNumber}`;
}

/**
 * Parse order number from URL search string.
 * Accepts formats: "?order=RE-00142", "?order=RE-00142&foo=bar"
 * Returns null if no valid order parameter found.
 */
export function parseOrderParam(search: string): string | null {
  const params = new URLSearchParams(search);
  const order = params.get("order");
  if (!order) return null;

  const trimmed = order.trim();
  if (trimmed.length === 0) return null;

  return trimmed;
}

/**
 * Extract UTM source from URL search string.
 */
export function parseUtmSource(search: string): string | null {
  const params = new URLSearchParams(search);
  return params.get("ref") ?? params.get("utm_source") ?? null;
}
