-- Create orders table for konfigurator rolet plisowanych
-- Order numbers are auto-generated by trigger in format RE-XXXXX

-- Sequence for order numbers
CREATE SEQUENCE orders_seq START WITH 1 INCREMENT BY 1;

-- Orders table
CREATE TABLE orders (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  order_number TEXT UNIQUE NOT NULL DEFAULT '',
  config JSONB NOT NULL DEFAULT '{}',
  price DECIMAL(10, 2) NOT NULL DEFAULT 0,
  allegro_units INT NOT NULL DEFAULT 0,
  utm_source TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Trigger function to set order_number from sequence
CREATE OR REPLACE FUNCTION set_order_number()
RETURNS TRIGGER AS $$
BEGIN
  NEW.order_number := 'RE-' || LPAD(nextval('orders_seq')::text, 5, '0');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger on INSERT
CREATE TRIGGER trg_set_order_number
  BEFORE INSERT ON orders
  FOR EACH ROW
  EXECUTE FUNCTION set_order_number();

-- B-tree index on order_number for fast lookups
CREATE INDEX idx_orders_order_number ON orders (order_number);

-- Enable Row Level Security
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- RLS Policy: public SELECT by order_number
CREATE POLICY "Allow public select by order_number"
  ON orders
  FOR SELECT
  TO anon
  USING (true);

-- RLS Policy: public INSERT
CREATE POLICY "Allow public insert"
  ON orders
  FOR INSERT
  TO anon
  WITH CHECK (true);
